// js/niveles/datanivel1.js
import { TIPOS_CASILLA, ITEMS } from '../constants.js';
// 1. DEFINICIÓN DE COORDENADAS (Debe estar declarada antes del export)
const COORDENADAS = [
 { left: 49.44, top: 58.46 },
 { left: 53.16, top: 61.51 },
 { left: 55.98, top: 65.23 },
{ left: 58.81, top: 67.26 },
 { left: 61.25, top: 69.46 },
 { left: 64.07, top: 72.17 },
 { left: 66.89, top: 74.88 },
 { left: 69.97, top: 77.08 },
 { left: 73.57, top: 79.79 },
 { left: 72.29, top: 84.35 },
 { left: 69.33, top: 86.22 },
 { left: 66.00, top: 88.42 },
 { left: 62.53, top: 90.62 },
 { left: 58.94, top: 91.97 },
 { left: 55.60, top: 92.82 },
 { left: 52.26, top: 93.66 },
 { left: 48.28, top: 94.00 },
 { left: 44.30, top: 93.15 },
 { left: 40.19, top: 92.31 },
{ left: 37.50, top: 89.60 },
 { left: 34.67, top: 86.55 },
 { left: 31.46, top: 83.85 },
 { left: 27.49, top: 83.51 },
 { left: 23.76, top: 80.97 },
 { left: 23.76, top: 75.89 },
 { left: 27.61, top: 73.35 },
 { left: 31.46, top: 72.00 },
 { left: 34.67, top: 69.29 },
 { left: 36.09, top: 65.91 },
 { left: 35.32, top: 60.49 },
 { left: 33.65, top: 55.42 },
 { left: 32.11, top: 51.19 },
 { left: 30.95, top: 46.95 },
 { left: 31.72, top: 41.88 },
 { left: 34.67, top: 38.66 },
 { left: 37.37, top: 35.62 },
 { left: 38.65, top: 30.71 },
 { left: 38.78, top: 25.12 },
 { left: 38.27, top: 20.72 },
 { left: 36.09, top: 15.82 },
 { left: 34.16, top: 10.40 },
 { left: 33.13, top: 4.99 },
];
// 2. DEFINICIÓN DE CASILLAS (Debe estar declarada antes del export)
const CASILLAS = [
    { tipo: 'inicio', titulo: 'Inicio de la Aventura', descripcion: 'Comienzas tu viaje por la Provincia de Imbabura. ¡Mucha suerte!', recompensa: null },
    { tipo: 'lugar_emblematico', titulo: 'HELADOS DE PAILA', imagen: 'assets/lugares/nivel1/helados_paila.png', descripcion: 'Has llegado a la cuna de los famosos helados de paila. ¡Obtienes +50 puntos y +1 helado!', recompensa: { puntos: 50, item: 'helado' } },
    { tipo: 'camino', titulo: 'Ruta Sencilla', descripcion: 'Un camino simple, sin eventos. Continúa avanzando.', recompensa: null },
    { tipo: 'dato_curioso', titulo: 'Dato Curioso: Helados', descripcion: 'Uno de los acompañantes más frecuentes en el consumo de los helados de paila es la quesadilla. ¡Ganas +50 puntos y +1 Helado!', recompensa: { puntos: 50, item: 'helado' } },
    { tipo: 'pregunta', titulo: 'Pregunta: Helados de Paila', pregunta: '¿Cuál es el nombre de la promotora de los helados de paila más reconocida?', opciones: ['María Chuga', 'Rosalía Suárez', 'Anita Benavides'], respuestaCorrecta: 1, recompensa: { correcta: { puntos: 20, item: 'helado', feedback: "¡Correcto! Rosalía Suárez es la pionera. Ganas 20 puntos y 1 Helado." }, incorrecta: { puntosPerdidos: 15, feedback: "Respuesta incorrecta. La promotora más famosa es Rosalía Suárez. Pierdes 15 puntos." } } },
    { tipo: 'dato_curioso', titulo: 'Dato Curioso: Economía', descripcion: 'La producción y comercialización de helados dinamiza la agricultura y la economía locales. ¡Ganas +50 puntos!', recompensa: { puntos: 50, item: 'helado' } },
    { tipo: 'evento', subtipo: 'trampa_item', titulo: 'Trampa del Antojo', condicionItem: 'helado', text_fail: '¡Se te antoja un helado! Te distraes pensando en volver a la paila. Retrocedes 1 casilla.', move_fail: -1, text_success: '¡Oh no! Por la emoción del viaje, se te cae el helado que traías. Pierdes 1 Helado, pero por suerte no retrocedes.', itemLost: 'helado', move_success: 0 },
    { tipo: 'pregunta', titulo: 'Pregunta: Instrumentos', pregunta: '¿Cuál es el instrumento más característico en la elaboración de los helados de paila?', opciones: ['Paila de cobre', 'Banca de madera', 'Congelador'], respuestaCorrecta: 0, recompensa: { correcta: { puntos: 20, feedback: "¡Correcto! La paila de cobre es esencial. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. El instrumento clave es la paila de cobre. Pierdes 15 puntos." } } },
    { tipo: 'lugar_emblematico', titulo: 'MIRADOR DE ANGOCHAGUA', imagen: 'assets/lugares/nivel1/mirador_muchanajurumi.png', descripcion: 'Disfrutas de una vista espectacular desde el mirador Mucha Naju Rumi. ¡Obtienes +50 puntos y 1 árbol!', recompensa: { puntos: 50, item: 'arbol' } },
    { tipo: 'dato_curioso', titulo: 'Dato Curioso: Mucha Naju Rumi', descripcion: 'El mirador Mucha Naju Rumi está a una altitud de 2880 msnm. ¡Ganas +50 puntos y 1 Árbol!', recompensa: { puntos: 50, item: 'arbol' } },
    { tipo: 'camino', titulo: 'Camino de Montaña', descripcion: 'El sendero se vuelve empinado. ¡Sigue adelante!', recompensa: null },
    { tipo: 'pregunta', titulo: 'Pregunta: Idioma', pregunta: '¿En qué lengua está escrito Mucha Naju Rumi?', opciones: ['Inglés', 'Alemán', 'Kichwa'], respuestaCorrecta: 2, recompensa: { correcta: { puntos: 20, feedback: "¡Correcto! Está en Kichwa. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. La lengua es Kichwa. Pierdes 15 puntos." } } },
    { tipo: 'evento', subtipo: 'trampa_movimiento', titulo: 'Neblina Desorientadora', descripcion: 'Una densa neblina cubre el mirador y te desorientas por completo. Regresas 3 casillas.', movimiento: -3 },
    { tipo: 'camino', titulo: 'Descenso', descripcion: 'El camino es más fácil aquí. Aprovecha para descansar.', recompensa: null },
    { tipo: 'dato_curioso', titulo: 'Dato Curioso: Volcanes', descripcion: 'Desde este mirador se pueden apreciar varios volcanes, tales como: Taita Imbabura, Cubilche, Cuzín. ¡Ganas +50 puntos y 1 Árbol!', recompensa: { puntos: 50, item: 'arbol' } },
    { tipo: 'pregunta', titulo: 'Pregunta: Traducción', pregunta: '¿Conoces la traducción de Mucha Naju Rumi al español?', opciones: ['Lugar donde se besan las rocas', 'Lugar donde se rompen las rocas', 'Lugar donde brincan las rocas'], respuestaCorrecta: 0, recompensa: { correcta: { puntos: 20, feedback: "¡Excelente! Significa 'Lugar donde se besan las rocas'. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. La traducción es 'Lugar donde se besan las rocas'. Pierdes 15 puntos." } } },
    { tipo: 'dato_curioso', titulo: 'Dato Curioso: Flora', descripcion: 'En el trayecto al mirador se pueden observar una variedad de plantas y árboles como: achupallas, alisos, eucaliptos. ¡Ganas +50 puntos y 1 Árbol!', recompensa: { puntos: 50, item: 'arbol' } },
    { tipo: 'evento', subtipo: 'ventaja_movimiento', titulo: 'Atajo Secreto', descripcion: 'Descubres un camino menos empinado y tomas un atajo. ¡Avanzas 2 casillas!', movimiento: 2 },
    { tipo: 'lugar_emblematico', titulo: 'PLAZA DE PONCHOS', imagen: 'assets/lugares/nivel1/plaza_deponchos.png', descripcion: 'Estás en el mercado artesanal más grande de Sudamérica. ¡Obtienes +50 puntos y +1 poncho!', recompensa: { puntos: 50, item: 'poncho' } },
    { tipo: 'camino', titulo: 'Pasaje Comercial', descripcion: 'Sientes el ambiente vibrante del comercio.', recompensa: null },
    { tipo: 'dato_curioso', titulo: 'Dato Cultural', descripcion: 'Alrededor de la plaza de ponchos se pueden encontrar espacios culturales para vivir las costumbres y tradiciones locales. ¡Ganas +50 puntos y 1 Poncho!', recompensa: { puntos: 50, item: 'poncho' } },
    { tipo: 'pregunta', titulo: 'Pregunta: Fama', pregunta: '¿La plaza de ponchos de Otavalo es una de las ferias artesanales más grandes de América Latina?', opciones: ['Sí', 'No'], respuestaCorrecta: 0, recompensa: { correcta: { puntos: 20, feedback: "¡Así es! Es famosa en todo el continente. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. Es una de las más grandes y famosas. Pierdes 15 puntos." } } },
    { tipo: 'dato_curioso', titulo: 'Dato de Artesanía', descripcion: "Además de textiles, en la plaza puedes encontrar figuras talladas en 'tagua', una semilla tan dura que se la conoce como 'marfil vegetal'. ¡Ganas +50 puntos y 1 Poncho!", recompensa: { puntos: 50, item: 'poncho' } },
    { tipo: 'lugar_emblematico', titulo: 'LAGUNA DE CUICOCHA', imagen: 'assets/lugares/nivel1/lago_cuicocha.png', descripcion: 'Navegas por el "Lago de los Dioses". ¡Obtienes +50 puntos y 1 canoa!', recompensa: { puntos: 50, item: 'canoa' } },
    { tipo: 'camino', titulo: 'Rodeando el Lago', descripcion: 'El paisaje volcánico te impresiona.', recompensa: null },
    { tipo: 'dato_curioso', titulo: 'Dato Cultural: Chacana', descripcion: 'En la Ruta Sagrada se pueden encontrar simbolismos de los pueblos originarios como la Chacana y el calendario lunar. ¡Ganas +50 puntos y 1 Canoa!', recompensa: { puntos: 50, item: 'canoa' } },
    { tipo: 'pregunta', titulo: 'Pregunta: Domo', pregunta: 'El domo interior más grande del lago Cuicocha, se llama:', opciones: ['Yaguarcocha', 'Cuicocha', 'Teodoro Wolf'], respuestaCorrecta: 2, recompensa: { correcta: { puntos: 20, feedback: "¡Correcto! Se llama Teodoro Wolf. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. El domo más grande es el Teodoro Wolf. Pierdes 15 puntos." } } },
    { tipo: 'evento', subtipo: 'trampa_item', titulo: 'El Viento de la Laguna', condicionItem: 'poncho', text_fail: '¡El viento helado de la laguna te golpea! No tienes poncho para abrigarte y el soroche te marea. Pierdes 3 puntos.', pointsLost_fail: 3, text_success: '¡El viento helado de la laguna te golpea! Por suerte, usas tu poncho para abrigarte. ¡Te salvas de perder puntos, pero pierdes 1 Poncho!', itemLost: 'poncho', pointsLost_success: 0 },
    { tipo: 'lugar_emblematico', titulo: 'FÁBRICA IMBABURA', imagen: 'assets/lugares/nivel1/fabrica_imbabura.png', descripcion: 'Visitas el histórico complejo textil. ¡Obtienes +50 puntos y 1 algodón!', recompensa: { puntos: 50, item: 'algodon' } },
    { tipo: 'evento', subtipo: 'ventaja_recompensa', titulo: 'Muestra de Algodón', descripcion: 'Llegas a la FÁBRICA IMBABURA, un lugar lleno de historia. ¡Ganas 30 puntos y una muestra de Algodón!', recompensa: { puntos: 30, item: 'algodon' } },
    { tipo: 'pregunta', titulo: 'Pregunta: Producción', pregunta: '¿Sabes qué tipo de telas se producían especialmente en Fábrica Imbabura?', opciones: ['Telas de poliester', 'Telas de algodón', 'Telas de poliester y algodón'], respuestaCorrecta: 1, recompensa: { correcta: { puntos: 20, feedback: "¡Correcto! Eran especialistas en telas de algodón. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. La producción principal era de telas de algodón. Pierdes 15 puntos." } } },
    { tipo: 'evento', subtipo: 'trampa_item', titulo: 'Peligro de Maquinaria', condicionItem: 'algodon', text_fail: '¡Qué descuido! Te acercas demasiado a la maquinaria. Te llevas un susto y te obligan a retroceder 2 casillas.', move_fail: -2, text_success: '¡Por un descuido, una de las máquinas engancha tu materia prima! Logras rescatarla, pero pierdes 1 Algodón en el proceso.', itemLost: 'algodon', move_success: 0 },
    { tipo: 'dato_curioso', titulo: 'Dato Histórico: Fundación', descripcion: 'La fecha de fundación de la Fábrica Imbabura es 1924. ¡Ganas +50 puntos y 1 Algodón!', recompensa: { puntos: 50, item: 'algodon' } },
    { tipo: 'pregunta', titulo: 'Pregunta: Cantón', pregunta: '¿En qué cantón está localizada la Fábrica Imbabura?', opciones: ['Otavalo', 'Cotacachi', 'Antonio Ante'], respuestaCorrecta: 2, recompensa: { correcta: { puntos: 20, feedback: "¡Exacto! Se encuentra en Antonio Ante. Ganas 20 puntos." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. La fábrica está en el cantón Antonio Ante. Pierdes 15 puntos." } } },
    { tipo: 'dato_curioso', titulo: 'Dato Histórico: Dinamización', descripcion: 'Fábrica Imbabura, en su época de apogeo dinamizó la producción agrícola de algodón de los valles de Salinas y el Chota. ¡Ganas +50 puntos y 1 Algodón!', recompensa: { puntos: 50, item: 'algodon' } },
    { tipo: 'camino', titulo: 'Tramo Final', descripcion: 'Estás cerca de la meta final, ¡sigue adelante!', recompensa: null },
    { tipo: 'lugar_emblematico', titulo: 'MONTAÑA DE LUZ', imagen: 'assets/lugares/nivel1/montaña_deluz.png', descripcion: 'Llegas a un lugar de paz y sanación. ¡Obtienes +50 puntos y 1 árbol simbólico!', recompensa: { puntos: 50, item: 'arbol' } },
    { tipo: 'camino', titulo: 'Sendero de Reflexión', descripcion: 'Un lugar tranquilo para recargar energías.', recompensa: null },
    { tipo: 'pregunta', titulo: 'Pregunta: Historia Local', pregunta: '¿Cuál era el nombre original de la parroquia Pablo Arenas?', opciones: ['Cruzcacho', 'Angochagua', 'San Pablo'], respuestaCorrecta: 0, recompensa: { correcta: { puntos: 20, item: 'arbol', feedback: "¡Correcto! El nombre original era Cruzcacho. Ganas 20 puntos y 1 Árbol." }, incorrecta: { puntosPerdidos: 15, feedback: "Incorrecto. La respuesta correcta es Cruzcacho. Pierdes 15 puntos." } } },
    { tipo: 'evento', subtipo: 'trampa_puntos', titulo: 'Distracción en el Geoparque', descripcion: "¡El paisaje desde la 'Montaña de Luz' es espectacular! Te distraes tanto admirando el Geoparque que se te hace tarde. Pierdes 15 puntos.", pointsLost: 15 },
    { tipo: 'dato_curioso', titulo: 'Dato Curioso: Productos Orgánicos', descripcion: 'En Montaña de Luz se ofrecen servicios de alimentación preparados con productos orgánicos, cultivados en el mismo lugar. ¡Ganas +50 puntos y 1 Árbol!', recompensa: { puntos: 50, item: 'arbol' } },
    { tipo: 'fin', titulo: '¡FINAL DE LA AVENTURA!', descripcion: '¡Felicidades, has culminado la Aventura en Imbabura!', recompensa: null }
];

// 3. EXPORTACIÓN FINAL (Ahora sí funcionará porque las variables de arriba existen)
export const NIVEL_1_DATA = {
    coordenadas: COORDENADAS,
    casillas: CASILLAS
};